name: Compile & test on push and PR

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Compile & Test
        run: make all